name: QuakeCraft
main: com.gmail.filoghost.quakecraft.QuakeCraft
version: 1.0

softdepend: [WildCommons, HolographicDisplays]

commands:
  quake:
    description: Comando principale per QuakeCraft (Admin).
    usage: /<command> [args]
    permission: quakecraft.quake
  spawn:
    description: Torna allo spawn.
    usage: /<command>
    aliases: [lobby]
  arena:
    description: Comandi per gestire le arene (Admin).
    usage: /<command> [args]
    permission: quakecraft.arena
  coins:
    description: Comandi per gestire i coins.
    usage: /<command> [args]
    aliases: [coin]
  killall:
    description: Uccidi tutti i mob (Admin)
    usage: /<command>
    permission: quakecraft.killall
  start:
    description: Fai partire una arena.
    usage: /<command>
    permission: quakecraft.start
  rank:
    description: Impostazioni classifica (Admin).
    usage: /<command>
    permission: quakecraft.rank
  stats:
    description: Statistiche.
    usage: /<command>
  classifica:
    description: Classifica uccisioni.
    usage: /<command>
  test:
    description: Comando di prova (Admin)
    usage: /<command> [args]
    permission: quakecraft.test